# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev
version: 3

dotenv: [".env"]
set: [pipefail]
shopt: [globstar]

env:
  CGO_ENABLED: 0

tasks:
  init:
    desc: Setup dev env (anything that pixi can't install and setup for us).
    cmds:
      - lefthook install -f
      - git config pull.rebase true
      - git config core.editor "code --wait"
      - git config commit.template "$PWD/.gitmsgtpl"
      - "{{if .CI}}git config --global user.name github-actions[bot]{{end}}"
      - "{{if .CI}}git config --global user.email github-actions[bot]@users.noreply.github.com{{end}}"

  install-go-tools:
    desc: Installs all the golang dev tooling that vscode needs (for some reason the auto install that VsCode tries to run fails)
    cmds:
      - go install -v github.com/cweill/gotests/gotests@v1.6.0
      - go install -v github.com/josharian/impl@v1.4.0
      - go install -v github.com/haya14busa/goplay/cmd/goplay@v1.0.0
      - go install -v github.com/go-delve/delve/cmd/dlv@latest
      - go install -v golang.org/x/tools/gopls@latest

  lint:
    desc: Lints our code to ensure it remains of a high quality.
    cmds:
      - dprint check
      - golangci-lint run

  fmt:
    desc: Formats our code to ensure it looks consistent.
    cmds:
      - dprint fmt

  build:
    desc: Builds the terraform provider executables for local use with the example stack
    cmds:
      - mkdir -p ./bin
      - goreleaser build --clean --snapshot --single-target -o ./bin/terraform-provider-denobridge{{if eq OS "windows"}}.exe{{end}}

  test:
    desc: Runs the test suite (including tf acceptance tests)
    env:
      TF_ACC: 1
      TF_LOG: DEBUG
    cmds:
      - go test -v ./internal/provider/... {{.CLI_ARGS}}

  config:generate:
    desc: Generates the Terraform/OpenTofu CLI config file with absolute paths
    vars:
      TF_CLI_CONFIG_FILE: "{{.ROOT_DIR}}/.tofurc"
      TF_BIN_DIR: "{{.ROOT_DIR}}/bin"
    env:
      TF_CLI_CONFIG_FILE: "{{.TF_CLI_CONFIG_FILE | fromSlash}}"
      TF_BIN_DIR: "{{.TF_BIN_DIR | fromSlash}}"
    cmds:
      - |
          echo 'Deno.writeTextFileSync(Deno.env.get("TF_CLI_CONFIG_FILE"), `
            provider_installation {

              dev_overrides {
                "registry.terraform.io/brad-jones/denobridge" = "${Deno.env.get("TF_BIN_DIR").replaceAll("\\", "\\\\")}"
              }

              direct {}
            }
          `);' | deno run -qA -

  run:tf:
    desc: Run any terraform command against the example stack.
    summary: |
      This is useful for exploratory testing and development.

      Eg: task run:terraform -- apply
    deps:
      - build
      - config:generate
    env:
      TF_LOG: WARN
      TF_CLI_CONFIG_FILE: "{{.ROOT_DIR}}/.tofurc"
    cmds:
      - cd ./example && terraform {{.CLI_ARGS}}

  run:tofu:
    desc: Run any tofu command against the example stack.
    summary: |
      This is useful for exploratory testing and development.

      Eg: task run:tofu -- apply
    deps:
      - build
      - config:generate
    env:
      TF_LOG: WARN
      TF_CLI_CONFIG_FILE: "{{.ROOT_DIR}}/.tofurc"
    cmds:
      - cd ./example && tofu {{.CLI_ARGS}}

  run:clean:
    desc: Deletes any state associated with the example stack
    cmds:
      - |
          echo '
          function remove(path: string) {
            try {
              Deno.removeSync(path);
            } catch (error) {
              if (!(error instanceof Deno.errors.NotFound)) {
                throw error;
              }
            }
          }
          remove("./example/terraform.tfstate");
          remove("./example/terraform.tfstate.backup");
          remove("./example/bjc.mx");
          ' | deno run -qA -
