openapi: 3.0.3
info:
  title: DenoBridge Ephemeral Resource API
  version: 1.0.0
  description: |
    HTTP API contract for Terraform denobridge_ephemeral_resource implementations.

    This specification defines the endpoints that a Deno TypeScript script must implement
    to provide ephemeral resource functionality in Terraform.

    Ephemeral resources are short-lived resources that exist only during a Terraform
    operation (plan/apply). They are typically used for temporary credentials, tokens,
    or other time-sensitive data. The provider will start your Deno script as an HTTP
    server and manage the ephemeral resource lifecycle through these endpoints.

servers:
  - url: http://localhost:{port}
    description: Local Deno HTTP server (port assigned dynamically)
    variables:
      port:
        default: "0"
        description: Port dynamically assigned by the provider

paths:
  /health:
    get:
      summary: Health check endpoint
      description: |
        The provider polls this endpoint until it receives a successful response
        before attempting to call any other lifecycle endpoints.
      responses:
        "204":
          description: Server is ready to accept requests

  /open:
    post:
      summary: Open/create the ephemeral resource
      description: |
        Opens or creates an ephemeral resource instance. This is called when the
        ephemeral resource is first accessed during a Terraform operation.

        The response can include:
        - result: The data to be made available to Terraform
        - renewAt: Unix timestamp (seconds) when the resource should be renewed
        - private: Private data to be passed to /renew and /close endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - props
              properties:
                props:
                  type: object
                  description: Input properties for creating the ephemeral resource
                  additionalProperties: true
            example:
              props:
                prefix: "example-"
      responses:
        "200":
          description: Ephemeral resource opened successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - result
                properties:
                  result:
                    type: object
                    description: Data to be made available to Terraform
                    additionalProperties: true
                  renewAt:
                    type: integer
                    format: int64
                    description: Unix timestamp (seconds) when this resource should be renewed
                  private:
                    type: object
                    description: Private data stored by provider and passed to /renew and /close
                    additionalProperties: true
              example:
                result:
                  uuid: "550e8400-e29b-41d4-a716-446655440000"
        "4XX":
          description: Client error during resource open
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "5XX":
          description: Server error during resource open
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /renew:
    post:
      summary: Renew the ephemeral resource (optional)
      description: |
        Optional endpoint to renew an ephemeral resource that may expire.

        This is called at the time specified by the renewAt value returned
        from /open or a previous /renew call. If this endpoint is not
        implemented (returns 404), the provider will not attempt to renew.

        The request body contains the private data returned from /open or
        the previous /renew call.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Private data previously returned from /open or /renew
              additionalProperties: true
      responses:
        "200":
          description: Resource renewed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  renewAt:
                    type: integer
                    format: int64
                    description: New Unix timestamp (seconds) when this resource should be renewed again
                  private:
                    type: object
                    description: Updated private data to be stored by provider
                    additionalProperties: true
        "404":
          description: Endpoint not implemented (no renewal needed)
        "4XX":
          description: Client error during renewal
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "5XX":
          description: Server error during renewal
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /close:
    post:
      summary: Close/cleanup the ephemeral resource (optional)
      description: |
        Optional endpoint to clean up an ephemeral resource when it's no longer needed.

        This is called when the Terraform operation completes or when the resource
        is no longer referenced. If this endpoint is not implemented (returns 404),
        the provider will not attempt cleanup.

        The request body contains the private data returned from /open or
        the most recent /renew call.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Private data previously returned from /open or /renew
              additionalProperties: true
      responses:
        "200":
          description: Resource closed successfully
        "204":
          description: Resource closed successfully (no content)
        "404":
          description: Endpoint not implemented (no cleanup needed)
        "4XX":
          description: Client error during close
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "5XX":
          description: Server error during close
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message describing what went wrong
