openapi: 3.0.3
info:
  title: DenoBridge Action API
  version: 1.0.0
  description: |
    HTTP API contract for Terraform denobridge_action implementations.

    This specification defines the endpoints that a Deno TypeScript script must implement
    to provide action functionality in Terraform.

    Actions are operations that can be invoked during Terraform execution but don't
    manage resources or data. They're useful for tasks like notifications, validations,
    or triggering external workflows. The provider will start your Deno script as an
    HTTP server and call the /invoke endpoint with streaming JSONL response support.

servers:
  - url: http://localhost:{port}
    description: Local Deno HTTP server (port assigned dynamically)
    variables:
      port:
        default: "0"
        description: Port dynamically assigned by the provider

paths:
  /health:
    get:
      summary: Health check endpoint
      description: |
        The provider polls this endpoint until it receives a successful response
        before attempting to call any other endpoints.
      responses:
        "204":
          description: Server is ready to accept requests

  /invoke:
    post:
      summary: Invoke the action
      description: |
        Executes the action with the provided input properties.

        The response should be a streaming JSONL (JSON Lines) format, where each line
        is a JSON object containing a "message" field. These messages are sent as
        progress events to Terraform and displayed to the user in real-time.

        This allows for long-running operations to provide feedback during execution.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - props
              properties:
                props:
                  type: object
                  description: Input properties for the action
                  additionalProperties: true
            example:
              props:
                path: "/tmp/action-file.txt"
                content: "Action content"
      responses:
        "200":
          description: Action invoked successfully with streaming progress
          content:
            application/jsonl:
              schema:
                type: string
                description: |
                  Newline-delimited JSON stream where each line is a JSON object
                  with a "message" field containing progress information
                format: jsonl
              example: |
                {"message":"about to write file"}
                {"message":"file written"}
        "4XX":
          description: Client error during action invocation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "5XX":
          description: Server error during action invocation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message describing what went wrong

    ProgressMessage:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Progress message to display to the user
      example:
        message: "Processing step 1 of 3"
