openapi: 3.0.3
info:
  title: DenoBridge Datasource API
  version: 1.0.0
  description: |
    HTTP API contract for Terraform denobridge_datasource implementations.

    This specification defines the endpoints that a Deno TypeScript script must implement
    to provide data source functionality in Terraform.

    Data sources are read-only and are used to fetch external data that can be used
    elsewhere in Terraform configuration. The provider will start your Deno script
    as an HTTP server and call the /read endpoint to fetch data.

servers:
  - url: http://localhost:{port}
    description: Local Deno HTTP server (port assigned dynamically)
    variables:
      port:
        default: "0"
        description: Port dynamically assigned by the provider

paths:
  /health:
    get:
      summary: Health check endpoint
      description: |
        The provider polls this endpoint until it receives a successful response
        before attempting to call any other endpoints.
      responses:
        "204":
          description: Server is ready to accept requests

  /read:
    post:
      summary: Fetch data from the data source
      description: |
        Retrieves data based on the provided input properties.

        Data sources are read-only and do not create or modify any infrastructure.
        They are evaluated during the plan phase and used to fetch external data
        that can be referenced in other Terraform resources.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - props
              properties:
                props:
                  type: object
                  description: Input properties that specify what data to fetch
                  additionalProperties: true
            example:
              props:
                value: "example-string"
      responses:
        "200":
          description: Data fetched successfully
          content:
            application/json:
              schema:
                type: object
                description: The fetched data that will be available to Terraform
                additionalProperties: true
              example:
                hashedValue: "50d858e0985ecc7f60418aaf0cc5ab587f42c2570a884095a9e8ccacd0f6545c"
        "4XX":
          description: Client error during data fetch
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "5XX":
          description: Server error during data fetch
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message describing what went wrong
